# SPDX-FileCopyrightText: 2026 W. Taylor Farrington
# SPDX-License-Identifier: Apache-2.0
"""The nine leak-prevention scanners (EP-6), as importable functions.

Every brief before EP-6 ran these checks by hand, once, and pasted the output
into a completion note. That does not scale and it does not survive a tired
session. Here they are enforcement: one function per check, each returning
findings rather than raising, so that one run reports the whole picture.

The nine checks, by id:

===================  ==============================================================
``secrets``          token shapes and credential assignments, tree and full history
``phi``              MRN / DOB / NPI / SSN / phone / email / street-address shapes
``protected-text``   corpus paths in history, the D-74 budget, chapter-title runs
``identity``         user-profile paths, UNC paths, foreign drives, account, host
``roots``            the index and model roots outside documentation
``rights``           EP-5's licence, source-reference and verbatim rules
``badge``            the README badge resolves to a fully ticked evidence file
``modality``         the retired-modality stem (D-4, owner ruling OD-10)
``ledger``           shared passages with private planning state (D-2, OD-3)
===================  ==============================================================

A tenth id, ``allowlist``, is not a leak check: it is this module checking its
own rule-definition allowlist, and it reports a marker that suppressed nothing.
An exemption for a line that does not need one is a hole waiting for a future
edit.

**These scanners are defense in depth. They are not proof that nothing leaked.**
The proof is the pre-publication review packet in
`epppsynth/docs/pre-publication-checklist.md`, performed by a human, recorded
with a date and a commit hash.

**Split literals.** Every rule literal in this file is assembled from fragments
across a ``+``, so that the file defining a rule does not match the rule it
defines. EP-0 set the convention for prose; it applies to code for the same
reason, and it is why this module needs no exemption of its own.

**No finding prints matched text.** A finding is a check id, a path, a line, a
rule name and a static explanation of the rule. Printing the match would make a
CI log the very artifact the secrets check exists to prevent.
"""

from __future__ import annotations

import argparse
import os
import pathlib
import re
import subprocess
import sys
from collections.abc import Iterable, Sequence
from dataclasses import dataclass, field

from ..rights.check import check_locators  # noqa: F401  (documented, run via run_all)
from ..rights.paths import repo_root
from . import ledger as ledger_module
from .allowlist import (
    CANARY_ALLOWLIST,
    CANARY_REASON,
    MODALITY_EXEMPTIONS,
    Skip,
    is_canary,
    marked_lines,
)

# ── the check ids ────────────────────────────────────────────────────────────

CHECKS: tuple[str, ...] = (
    "secrets",
    "phi",
    "protected-text",
    "identity",
    "roots",
    "rights",
    "badge",
    "modality",
    "ledger",
)

#: Not one of the nine. `allowlist` is the allowlist checking itself.
SELF_CHECK = "allowlist"

PASSED, FAILED, SKIPPED = "passed", "failed", "skipped"

MARKER_REASON = "rule-definition"

#: Every reason a scanner may decline to report a match, with what it means. A
#: reason with no entry here would print bare, which is how an exemption stops
#: being legible; the summary is the only place an exemption is ever visible.
SKIP_REASONS: dict[str, str] = {
    MARKER_REASON: (
        "the line carries the rule-definition marker and matched a rule it defines "
        "(line-scoped; never a block, a file, a directory or a pattern)"
    ),
    "project-contact": (
        "the one email address this repository already publishes in its own commit "
        "metadata (owner ruling OD-7)"
    ),
    "lockfile-byte-size": (
        "a `size =` value in the resolver lockfile, which is machine-generated and "
        "regenerated byte-identically by `uv sync --locked`"
    ),
    "git-object-id": (
        "an all-digit abbreviated object id that `git rev-parse` resolves in this "
        "repository; a run git cannot resolve stays a finding"
    ),
    "bibliographic-identity": (
        "the stem falls inside a source identifier or citation title declared in "
        "sources.yaml, which D-74 requires this project to be able to cite "
        "(owner ruling OD-14)"
    ),
    "modality-exemption": (
        "one of the three owner-ratified files of the OD-10 exemption table, each "
        "carrying its reason"
    ),
    "canary-directory": (
        "a file diff under the one allowlisted canary directory, matched by the same "
        "exact path the tree sweep uses; commit headers and messages are never exempt"
    ),
}


# ── findings ─────────────────────────────────────────────────────────────────


@dataclass(frozen=True)
class Finding:
    """One rule violation: where it is, which rule, and what the rule means.

    Deliberately *not* the matched text. A reader locates the finding from the
    path and line; a CI log never carries the thing that leaked.
    """

    check: str
    path: str
    line: int | None
    rule: str
    detail: str
    hint: str = ""

    @property
    def where(self) -> str:
        return f"{self.path}:{self.line}" if self.line is not None else self.path

    def render(self, *, fix_hints: bool = False) -> str:
        out = f"{self.check}\t{self.where}\t{self.rule}\t{self.detail}"
        if fix_hints and self.hint:
            out += f"\n\t\thint: {self.hint}"
        return out


@dataclass
class CheckResult:
    check: str
    status: str = PASSED
    findings: list[Finding] = field(default_factory=list)
    skips: list[Skip] = field(default_factory=list)
    note: str = ""

    def fail(self) -> CheckResult:
        if self.findings:
            self.status = FAILED
        return self


@dataclass
class ScanReport:
    root: pathlib.Path
    results: list[CheckResult] = field(default_factory=list)
    history: bool = False

    @property
    def findings(self) -> list[Finding]:
        return [finding for result in self.results for finding in result.findings]

    @property
    def skips(self) -> list[Skip]:
        return [skip for result in self.results for skip in result.skips]

    @property
    def ok(self) -> bool:
        return not self.findings

    def render(self, *, fix_hints: bool = False) -> str:
        width = max(len(result.check) for result in self.results) if self.results else 0
        lines = [f"epppsynth scan - {self.root}"]
        for result in self.results:
            note = f"  {result.note}" if result.note else ""
            count = f"{len(result.findings)} finding(s)" if result.findings else ""
            lines.append(f"  {result.check:<{width}}  {result.status:<7}{note}  {count}".rstrip())
        lines.append("")
        if self.findings:
            lines.append(f"{len(self.findings)} finding(s) - check id, path:line, rule, meaning:")
            lines.extend(finding.render(fix_hints=fix_hints) for finding in self.findings)
            lines.append("")
        lines.append(
            f"{len(self.skips)} skipped line(s), by reason - every exemption, inventoried:"
        )
        by_reason: dict[str, dict[str, set[int]]] = {}
        for skip in self.skips:
            paths = by_reason.setdefault(skip.reason, {})
            numbers = paths.setdefault(skip.path, set())
            if skip.line is not None:
                numbers.add(skip.line)
        for reason in sorted(by_reason):
            entries = by_reason[reason]
            unique = sum(max(len(numbers), 1) for numbers in entries.values())
            suppressed = sum(1 for skip in self.skips if skip.reason == reason)
            counts = f"{unique} line(s)"
            if suppressed != unique:
                counts += f", {suppressed} suppression(s)"
            lines.append(f"  {reason}: {counts} - {SKIP_REASONS.get(reason, '')}".rstrip())
            for path in sorted(entries):
                numbers = ",".join(str(number) for number in sorted(entries[path]))
                lines.append(f"    {path}{':' + numbers if numbers else ''}")
        return "\n".join(lines)


# ── rules ────────────────────────────────────────────────────────────────────


@dataclass(frozen=True)
class Rule:
    name: str
    pattern: re.Pattern[str]
    detail: str
    hint: str = ""


def _rule(name: str, pattern: str, detail: str, hint: str = "", flags: int = 0) -> Rule:
    return Rule(name, re.compile(pattern, flags), detail, hint)


# Check 1 — secrets. Each literal is split across a `+` so that this file does
# not carry the shapes it hunts for.
SECRET_RULES: tuple[Rule, ...] = (
    _rule(
        "github-token",
        "gh" + r"[pousr]_[A-Za-z0-9]{36}",
        "a GitHub token shape",
        "revoke the token at its issuer, then remove it from the tree and the history",
    ),
    _rule(
        "github-pat",
        "github" + r"_pat_[A-Za-z0-9_]{20,}",
        "a GitHub fine-grained personal-access-token shape",
        "revoke the token at its issuer, then remove it from the tree and the history",
    ),
    _rule(
        "provider-key",
        "sk" + r"-[A-Za-z0-9]{20,}",
        "a model-provider API-key shape",
        "revoke the key at its issuer; this project needs no provider key "
        "(D-8, no runtime network)",
    ),
    _rule(
        "aws-access-key",
        "AKI" + r"A[0-9A-Z]{16}",
        "an AWS access-key-id shape",
        "revoke the key, then remove it from the tree and the history",
    ),
    _rule(
        "slack-token",
        "xox" + r"[baprs]-[A-Za-z0-9-]{10,}",
        "a Slack token shape",
        "revoke the token, then remove it from the tree and the history",
    ),
    _rule(
        "private-key-block",
        "-----BEGIN" + r"[A-Z ]*PRIVATE" + " KEY-----",
        "a PEM private-key block",
        "rotate the key pair; a committed private key is compromised even after deletion",
    ),
    _rule(
        "credential-assignment",
        r"\b(?:password|passwd|passphrase)" + r"\s*[:=]\s*[\"'][^\"'\s]{6,}[\"']",
        "a credential assigned to a quoted literal",
        "move the value to an untracked local config file, on the D-60 pattern",
        re.IGNORECASE,
    ),
    _rule(
        "api-key-assignment",
        r"\bapi" + r"[_-]?key\s*[:=]\s*[\"'][^\"'\s]{6,}[\"']",
        "an API key assigned to a quoted literal",
        "move the value to an untracked local config file, on the D-60 pattern",
        re.IGNORECASE,
    ),
)

# Check 2 — PHI shapes. The digit-run rule is deliberately broad; what keeps it
# usable is the accounted-for inventory below, not a narrower pattern.
PROJECT_CONTACT = "william.t.farrington@gmail.com"

PHI_RULES: tuple[Rule, ...] = (
    _rule(
        "mrn-shaped-digit-run",
        r"\b\d{6,10}\b",
        "a six-to-ten digit run, the shape of a medical record number",
        "no real identifier may appear anywhere in this repository (D-8, GOVERNANCE §5)",
    ),
    _rule(
        "ssn-shaped",
        r"\b\d{3}-\d{2}-\d{4}\b",
        "a US social-security-number shape",
        "remove it; scenarios are manifestly fictional and carry no identifiers (D-36)",
    ),
    _rule(
        "date-of-birth-shaped",
        r"\b(?:0?[1-9]|1[0-2])[/-](?:0?[1-9]|[12]\d|3[01])[/-](?:19|20)\d{2}\b",
        "a month/day/year date, the shape of a date of birth",
        "scenarios state ages in bands, never dates (D-8)",
    ),
    _rule(
        "npi-shaped",
        r"\bNPI\b\s*[:#=]?\s*\d{10}\b",
        "a labelled ten-digit national provider identifier",
        "remove it; no real clinician is named or numbered in this repository",
        re.IGNORECASE,
    ),
    _rule(
        "phone-shaped",
        r"(?<!\d)\(?\d{3}\)?[-.\s]\d{3}[-.\s]\d{4}(?!\d)",
        "a ten-digit telephone-number shape",
        "crisis-line numbers belong in SAFETY.md §9 only, under the D-18 addendum",
    ),
    _rule(
        "email-address",
        r"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}",
        "an email address other than the project contact",
        "remove it; the only address this repository publishes is its own (owner ruling OD-7)",
    ),
    _rule(
        "street-address-fragment",
        r"\b\d{1,5}\s+[A-Z][a-z]+\s+"
        r"(?:Street|St|Avenue|Ave|Road|Rd|Lane|Ln|Drive|Dr|Boulevard|Blvd|Court|Ct)\b",
        "a street-address fragment",
        "scenarios name no place that could locate a person (D-8)",
    ),
)

# Check 4 — local paths and machine identity. The two declared roots are
# deliberately public (D-30, D-51) and are the only absolute paths permitted.
#: One regex-escaped backslash, and a colon-plus-backslash, built rather than
#: written: the rules for user-profile, UNC and absolute drive paths would
#: otherwise be user-profile, UNC and absolute drive paths.
_BS = chr(92) * 2
_DRIVE = ":" + _BS
IDENTITY_RULES: tuple[Rule, ...] = (
    _rule(
        "user-profile-path",
        "C:" + _BS + "Users" + _BS + "|" + "C:" + "/Users/",
        "a Windows user-profile path, which carries an account name",
        "write the path relative to the repository root, or split the literal across a `+`",
        re.IGNORECASE,
    ),
    _rule(
        "unc-path",
        r"(?<![\\\w])\\\\[A-Za-z0-9][A-Za-z0-9._-]*\\",
        "a UNC path, which is a machine name by definition",
        "remove it; no network share is part of this project (D-8, no runtime network)",
    ),
    _rule(
        "foreign-drive-letter",
        r"(?<![\w:])[A-Za-z]" + _DRIVE + r"(?!epppmodels|epppindex)",
        "an absolute drive path other than the two declared, deliberately public roots",
        "use a repository-relative path; only the model and index roots may be absolute",
    ),
)

# Check 5 — the two roots, permitted in documentation and forbidden everywhere
# else (D-16, D-51). The literals are split for the reason the module docstring
# gives: this file is code, so it may not contain them.
ROOT_RULES: tuple[Rule, ...] = (
    _rule(
        "index-root-outside-documentation",
        "C:" + r"[\\/]epppindex",
        "the local index root in code, a test, a fixture or a configuration default",
        "the roots are documentation-only; read them from configuration, never hard-code them",
        re.IGNORECASE,
    ),
    _rule(
        "model-root-outside-documentation",
        "C:" + r"[\\/]epppmodels",
        "the model root in code, a test, a fixture or a configuration default",
        "the roots are documentation-only; read them from configuration, never hard-code them",
        re.IGNORECASE,
    ),
)

# Check 8 — the retired modality term (D-4, owner ruling OD-10). A stem sweep,
# not a token sweep: EP-2 swept for the exact token and could not see the
# adjectival form.
MODALITY_STEM = "psycho" + "therap"
MODALITY_RULE = _rule(
    "retired-modality-stem",
    MODALITY_STEM,
    "the retired modality stem, outside the owner-ratified exemption table",
    "reword to the broader term; the exemption table grows only by a further owner ruling",
    re.IGNORECASE,
)

#: Suffixes read as documentation for check 5. Everything else is code, a test,
#: a fixture or a configuration file.
DOCUMENTATION_SUFFIXES = frozenset({".md", ".markdown", ".cff", ".txt"})
DOCUMENTATION_NAMES = frozenset({"NOTICE", "LICENSE", "LICENSE-CONTENT"})

#: The public prose the D-74 quotation budget is counted over. `epppsynth/tests`
#: is outside the input set by **scope, not by exemption** — it holds EP-5's
#: deliberately over-budget fixture, whose job is to make the counter fail, and a
#: waiver inside the set would be indistinguishable from a real one.
QUOTATION_EXCLUDED_PREFIX = "epppsynth/tests/"


# ── file access ──────────────────────────────────────────────────────────────


def tracked_files(root: pathlib.Path) -> tuple[str, ...]:
    """Every file git tracks, as repository-relative POSIX paths."""
    result = subprocess.run(
        ["git", "ls-files", "-z"], cwd=root, capture_output=True, check=True, text=True
    )
    return tuple(sorted(entry for entry in result.stdout.split("\0") if entry))


def read_text(root: pathlib.Path, path: str) -> str | None:
    """Read a tracked file as text, or `None` if it is binary or unreadable."""
    try:
        data = (root / path).read_bytes()
    except OSError:
        return None
    if b"\0" in data:
        return None
    return data.decode("utf-8", errors="replace")


def _is_documentation(path: str) -> bool:
    name = path.rsplit("/", 1)[-1]
    suffix = ("." + name.rsplit(".", 1)[-1]) if "." in name else ""
    return suffix in DOCUMENTATION_SUFFIXES or name in DOCUMENTATION_NAMES


def _line_of(text: str, offset: int) -> int:
    return text.count("\n", 0, offset) + 1


def _scan_rules(
    root: pathlib.Path,
    check: str,
    rules: Iterable[Rule],
    paths: Iterable[str],
    *,
    accounted: object = None,
) -> CheckResult:
    """Apply a rule set to a set of tracked files, honouring the line marker."""
    result = CheckResult(check)
    rules = tuple(rules)
    for path in paths:
        if is_canary(path):
            continue
        text = read_text(root, path)
        if text is None:
            continue
        marked = marked_lines(text)
        for rule in rules:
            for match in rule.pattern.finditer(text):
                line = _line_of(text, match.start())
                if line in marked:
                    result.skips.append(
                        Skip(path, line, MARKER_REASON, f"suppressed {check}/{rule.name}")
                    )
                    continue
                if accounted is not None:
                    reason = accounted(root, path, text, rule, match)  # type: ignore[operator]
                    if reason is not None:
                        result.skips.append(Skip(path, line, reason[0], reason[1]))
                        continue
                result.findings.append(
                    Finding(check, path, line, rule.name, rule.detail, rule.hint)
                )
    return result.fail()


# ── check 1 — secrets ────────────────────────────────────────────────────────

_DIFF_SPLIT = re.compile(r"(?m)^diff --git ")
_NEW_PATH = re.compile(r"(?m)^\+\+\+ b/(?P<path>.*)$")
_OLD_PATH = re.compile(r"(?m)^--- a/(?P<path>.*)$")


def history_segments(patch: str) -> list[tuple[str | None, str]]:
    """Split `git log -p --all` into `(path, text)`, one per file diff.

    The tree sweep skips the canary directory by exact path; the history sweep has
    to skip it by the same path or the committed fixtures make it permanently red
    — and a check that is always red is a check nobody reads. Splitting the patch
    is what makes the *same* allowlist apply to both.

    The first segment is everything before the first diff: commit headers and
    commit messages. Its path is `None`, so it is **never** exempt. A secret
    pasted into a commit message is a secret in the history.

    The path is read from the `+++ b/…` line, which runs to the end of the line
    and so survives a path with spaces; a deletion (`+++ /dev/null`) falls back to
    the `--- a/…` line.
    """
    parts = _DIFF_SPLIT.split(patch)
    segments: list[tuple[str | None, str]] = [(None, parts[0])]
    for part in parts[1:]:
        match = _NEW_PATH.search(part) or _OLD_PATH.search(part)
        path = match.group("path").strip() if match else None
        segments.append((path, part))
    return segments


def scan_secrets(root: pathlib.Path, *, history: bool = False) -> CheckResult:
    """Token shapes and credential assignments, over the tree and the history.

    The history sweep is `git log -p --all`, because an unreachable object is not
    a deleted one and this repository's history was erased and re-created once
    already. It is CI's job (`--history`); the pre-commit hook skips it for speed.
    """
    result = _scan_rules(root, "secrets", SECRET_RULES, tracked_files(root))
    if not history:
        result.note = "tree only — pass --history for the full-history sweep"
        return result.fail()

    completed = subprocess.run(
        ["git", "log", "-p", "--all"], cwd=root, capture_output=True, text=True, errors="replace"
    )
    if completed.returncode != 0:
        result.findings.append(
            Finding(
                "secrets",
                "<history>",
                None,
                "history-unreadable",
                "`git log -p --all` failed, so the history sweep did not run",
                "run the scan inside a git working tree with the full history fetched",
            )
        )
        return result.fail()

    patch = completed.stdout
    counts: dict[str, int] = {}
    exempt: dict[str, int] = {}
    for path, segment in history_segments(patch):
        for rule in SECRET_RULES:
            hits = len(rule.pattern.findall(segment))
            if not hits:
                continue
            if path is not None and is_canary(path):
                exempt[path] = exempt.get(path, 0) + hits
            else:
                counts[rule.name] = counts.get(rule.name, 0) + hits
    for rule in SECRET_RULES:
        hits = counts.get(rule.name, 0)
        if hits:
            result.findings.append(
                Finding(
                    "secrets",
                    "<history>",
                    None,
                    rule.name,
                    f"{hits} occurrence(s) of {rule.detail} in `git log -p --all`",
                    rule.hint,
                )
            )
    for path, hits in sorted(exempt.items()):
        result.skips.append(
            Skip(
                path,
                None,
                "canary-directory",
                f"{hits} occurrence(s) in the history of this file",
            )
        )
    result.note = f"tree + history ({len(patch)} patch bytes)"
    return result.fail()


# ── check 2 — PHI shapes ─────────────────────────────────────────────────────

_GIT_OBJECT_CACHE: dict[tuple[str, str], bool] = {}
_LOCKFILE_SIZE = re.compile(r"size\s*=\s*$")


def _is_git_object(root: pathlib.Path, candidate: str) -> bool:
    """Whether an all-digit run names a real object in this repository.

    A short commit hash that happens to be all digits is not a medical record
    number, and this repository records one in every completed roadmap row. The
    test is mechanical and fails closed: a run git cannot resolve is a finding.
    """
    key = (str(root), candidate)
    if key in _GIT_OBJECT_CACHE:
        return _GIT_OBJECT_CACHE[key]
    completed = subprocess.run(
        ["git", "rev-parse", "--verify", "--quiet", candidate + "^{object}"],
        cwd=root,
        capture_output=True,
        text=True,
    )
    _GIT_OBJECT_CACHE[key] = completed.returncode == 0
    return _GIT_OBJECT_CACHE[key]


def _accounted_phi(
    root: pathlib.Path, path: str, text: str, rule: Rule, match: re.Match[str]
) -> tuple[str, str] | None:
    """The two accounted-for digit runs, and the project's own contact address.

    Each is narrow, mechanical and inventoried in the scan summary. None of them
    is a path exemption: a leak in one of these files would still be reported by
    every other rule.
    """
    if rule.name == "email-address":
        if match.group(0) == PROJECT_CONTACT:
            return ("project-contact", "the address this repository already publishes (OD-7)")
        return None
    if rule.name != "mrn-shaped-digit-run":
        return None
    if _LOCKFILE_SIZE.search(text[max(0, match.start() - 12) : match.start()]):
        return ("lockfile-byte-size", "a `size =` value in a machine-generated resolver lockfile")
    if _is_git_object(root, match.group(0)):
        return (
            "git-object-id",
            "an all-digit abbreviated object id that resolves in this repository",
        )
    return None


def scan_phi(root: pathlib.Path) -> CheckResult:
    """PHI-shaped patterns across tracked files and fixtures, plus the D-36 rule."""
    result = _scan_rules(root, "phi", PHI_RULES, tracked_files(root), accounted=_accounted_phi)
    result.findings.extend(_scenario_attestations(root))
    scenarios = scenario_files(root)
    result.note = (
        f"{len(scenarios)} scenario fixture(s) checked for the D-36 attestation"
        if scenarios
        else "no scenario fixtures yet (the D-36 attestation check becomes live at EP-25)"
    )
    return result.fail()


#: Where EP-25 … EP-27 will put evaluation scenarios. Empty today; the check runs
#: over an empty set rather than not existing, so it becomes live by content.
SCENARIO_DIR = "epppsynth/eval/scenarios"

#: The attestation every scenario fixture must carry (D-36).
SCENARIO_ATTESTATION = "no real person"


def scenario_files(root: pathlib.Path) -> tuple[str, ...]:
    directory = root / SCENARIO_DIR
    if not directory.is_dir():
        return ()
    return tuple(
        sorted(
            p.relative_to(root).as_posix()
            for p in directory.rglob("*")
            if p.is_file() and p.suffix.lower() in {".yaml", ".yml", ".json", ".md"}
        )
    )


def _scenario_attestations(root: pathlib.Path) -> list[Finding]:
    findings = []
    for path in scenario_files(root):
        text = read_text(root, path) or ""
        if SCENARIO_ATTESTATION not in text.lower():
            findings.append(
                Finding(
                    "phi",
                    path,
                    None,
                    "missing-scenario-attestation",
                    "a scenario fixture with no `no real person` attestation (D-36)",
                    "add the attestation, or delete the fixture",
                )
            )
    return findings


# ── check 3 — protected text ─────────────────────────────────────────────────

CORPUS_DIR = "source material/"
CORPUS_README = "source material/README.md"

_TITLE_WORD = r"(?:[A-Z][a-z][\w'’-]*|of|the|and|a|an|to|in|on|for|with|from|as|at|by)"
CHAPTER_TITLE_LINE = re.compile(
    r"(?m)^[^\S\n]*(?:(?:[Cc]hapter|[Cc]h\.?|[Pp]art)[^\S\n]*(?P<a>\d{1,2})"
    r"|(?P<b>\d{1,2})[.)])[^\S\n]*[-–—:]?[^\S\n]*"
    r"(?P<title>[A-Z][a-z][\w'’-]*(?:[^\S\n]+" + _TITLE_WORD + r"){1,8})[^\S\n]*$"
)
#: Three or more title-shaped strings adjacent to an ordinal, with increasing
#: ordinals, inside this many lines of one another (D-74 addendum, ruling OD-6).
CHAPTER_TITLE_RUN = 3
CHAPTER_TITLE_WINDOW = 40


def chapter_title_runs(text: str) -> list[list[tuple[int, int, str]]]:
    """Sequences of ordinal-plus-title lines that reconstruct a source outline."""
    hits = [
        (_line_of(text, m.start()), int(m.group("a") or m.group("b")), m.group("title"))
        for m in CHAPTER_TITLE_LINE.finditer(text)
    ]
    runs = []
    for index in range(len(hits)):
        run = [hits[index]]
        for other in hits[index + 1 :]:
            if other[0] - run[-1][0] <= CHAPTER_TITLE_WINDOW and other[1] > run[-1][1]:
                run.append(other)
        if len(run) >= CHAPTER_TITLE_RUN:
            runs.append(run)
    return runs


def quotation_paths(root: pathlib.Path) -> tuple[pathlib.Path, ...]:
    """Every tracked markdown file outside the test tree.

    This widens EP-5's default set — `epppsynth/docs/**` plus `SAFETY.md` — to
    all public prose, which is the widening `rights.paths.quotation_scan_paths`
    named so that it would be a visible edit rather than an unstated default.
    """
    return tuple(
        root / path
        for path in tracked_files(root)
        if path.endswith(".md")
        and not path.startswith(QUOTATION_EXCLUDED_PREFIX)
        and not is_canary(path)
    )


def scan_protected_text(root: pathlib.Path) -> CheckResult:
    """No corpus path in any commit, no over-budget quotation, no outline."""
    from ..rights.quotes import count_quotations

    result = CheckResult("protected-text")

    completed = subprocess.run(
        ["git", "log", "--all", "--diff-filter=A", "--name-only", "--pretty=format:"],
        cwd=root,
        capture_output=True,
        text=True,
        errors="replace",
    )
    added = {line.strip() for line in completed.stdout.splitlines() if line.strip()}
    for path in sorted(added):
        if path.startswith(CORPUS_DIR) and path != CORPUS_README:
            result.findings.append(
                Finding(
                    "protected-text",
                    path,
                    None,
                    "corpus-path-in-history",
                    "a path under the copyrighted corpus directory was added in some commit",
                    "the corpus is never committed (D-10); this needs a history "
                    "rewrite, not a delete",
                )
            )

    report = count_quotations(quotation_paths(root))
    for finding in report.findings:
        path, _, line = finding.where.rpartition(":")
        result.findings.append(
            Finding(
                "protected-text",
                path or finding.where,
                int(line) if line.isdigit() else None,
                finding.rule,
                "over the D-74 quotation budget (25 words per quote, 150 per source)",
                "shorten the quotation, or state a reason in a `quote-budget-allow` comment",
            )
        )

    for path in tracked_files(root):
        if is_canary(path):
            continue
        text = read_text(root, path)
        if text is None:
            continue
        marked = marked_lines(text)
        for run in chapter_title_runs(text):
            if run[0][0] in marked:
                result.skips.append(
                    Skip(
                        path,
                        run[0][0],
                        MARKER_REASON,
                        "suppressed protected-text/chapter-title-sequence",
                    )
                )
                continue
            result.findings.append(
                Finding(
                    "protected-text",
                    path,
                    run[0][0],
                    "chapter-title-sequence",
                    f"{len(run)} title-shaped strings adjacent to a chapter ordinal, "
                    "in reading order",
                    "a source's outline is not publishable (D-74, OD-6); move the "
                    "spine to local config",
                )
            )
            break

    result.note = f"{len(report.quotations)} quoted span(s) counted over public prose"
    return result.fail()


# ── check 4 — local paths, account name, hostname ────────────────────────────


def identity_rules() -> tuple[Rule, ...]:
    """The fixed rules plus the operator's account name and machine hostname.

    Both are read from the environment **at run time** rather than recorded, so
    that no tracked file has to carry them in order for the check to exist. Names
    shorter than three characters are skipped: a two-letter word boundary sweep
    matches prose, and a check that cries wolf is a check nobody runs.
    """
    rules = list(IDENTITY_RULES)
    for name, variable, label in (
        ("operator-account-name", "USERNAME", "the operating account's name"),
        ("operator-account-name", "USER", "the operating account's name"),
        ("machine-hostname", "COMPUTERNAME", "the machine's hostname"),
        ("machine-hostname", "HOSTNAME", "the machine's hostname"),
    ):
        value = (os.environ.get(variable) or "").strip()
        if len(value) < 3:
            continue
        rule = _rule(
            name,
            r"\b" + re.escape(value) + r"\b",
            f"{label}, read from the environment at run time",
            "no machine identifier belongs in a public repository (D-3, GOVERNANCE §7)",
            re.IGNORECASE,
        )
        if all(existing.pattern.pattern != rule.pattern.pattern for existing in rules):
            rules.append(rule)
    return tuple(rules)


def scan_identity(root: pathlib.Path) -> CheckResult:
    return _scan_rules(root, "identity", identity_rules(), tracked_files(root))


# ── check 5 — the index and model roots in the wrong place ──────────────────


def scan_roots(root: pathlib.Path) -> CheckResult:
    """The two roots are deliberately public in documentation and nowhere else.

    They may be named in prose — `PRIVACY.md`, `DECISIONS.md` and the roadmap all
    name them, and that is the point of declaring them. In a `.py` file, a
    fixture, a workflow or a configuration default they are a data path, and a
    data path is how an index reaches a published artifact (R-19).
    """
    paths = [
        path
        for path in tracked_files(root)
        if not _is_documentation(path) or path.startswith(QUOTATION_EXCLUDED_PREFIX)
    ]
    result = _scan_rules(root, "roots", ROOT_RULES, paths)
    result.note = f"{len(paths)} non-documentation file(s)"
    return result


# ── check 6 — licence and rights ─────────────────────────────────────────────


def scan_rights(root: pathlib.Path) -> CheckResult:
    """EP-5's rules, wired rather than reinvented (EP-6 context paragraph)."""
    from ..rights.check import concept_paths, run_all
    from ..rights.coverage import licence_coverage
    from ..rights.load import load_sources
    from ..rights.model import RightsError
    from ..rights.paths import sources_yaml

    result = CheckResult("rights")

    try:
        registry = load_sources(sources_yaml(root))
    except RightsError as exc:
        result.findings.append(
            Finding(
                "rights",
                "epppsynth/registry/sources.yaml",
                None,
                "invalid-rights-record",
                f"the source rights record does not validate "
                f"({len(str(exc).splitlines())} problem(s))",
                "every source needs a complete, closed-enumeration rights row (D-62)",
            )
        )
        return result.fail()

    coverage = licence_coverage(root)
    for path in coverage.unmatched:
        result.findings.append(
            Finding(
                "rights",
                path,
                None,
                "licence-uncovered",
                "no REUSE.toml annotation covers this tracked file",
                "add the path to the Apache-2.0 or CC BY 4.0 annotation block (D-28, D-50)",
            )
        )
    for path in sorted(coverage.doubly_matched):
        result.findings.append(
            Finding(
                "rights",
                path,
                None,
                "licence-doubly-matched",
                "two REUSE.toml annotations disagree about this file's licence",
                "narrow one of the two path patterns so exactly one matches",
            )
        )
    for message in coverage.header_mismatches:
        path, _, detail = message.partition(": ")
        result.findings.append(
            Finding(
                "rights",
                path,
                None,
                "licence-header-mismatch",
                detail,
                '`precedence = "aggregate"` means the header wins; keep it equal to the table',
            )
        )
    for pattern in coverage.unused_patterns:
        result.findings.append(
            Finding(
                "rights",
                "REUSE.toml",
                None,
                "licence-pattern-unused",
                f"the pattern {pattern!r} matches no tracked file, which REUSE calls an error",
                "remove the pattern, or add the file it was written for",
            )
        )

    concepts = concept_paths(root)
    for finding in run_all(concepts, registry) if concepts else []:
        result.findings.append(
            Finding(
                "rights",
                finding.where.split(":")[0],
                None,
                finding.rule,
                finding.detail,
                "every concept cites a source with a rights row; verbatim never leaves the index",
            )
        )
    result.note = (
        f"{len(registry)} source row(s), {len(coverage.licence_of)} licensed file(s), "
        f"{len(concepts)} concept file(s)"
    )
    return result.fail()


# ── check 7 — the badge resolves to a ticked evidence file ──────────────────

BADGE_RE = re.compile(
    r"^status: (design|skeleton|self-evaluated — mode \([abc]\)|v1 — mode \([abc]\))$",
    re.MULTILINE,
)
EVIDENCE_DIR = "epppsynth/docs/evidence"
UNTICKED_BOX = re.compile(r"^\s*[-*]\s+\[ \]", re.MULTILINE)


def evidence_path_for(badge: str) -> str:
    """EP-2's badge → evidence-file mapping, implemented here (D-59)."""
    if badge == "design":
        return f"{EVIDENCE_DIR}/design.md"
    if badge == "skeleton":
        return f"{EVIDENCE_DIR}/skeleton.md"
    mode = badge[badge.index("(") + 1]
    rung = "gate" if badge.startswith("self-evaluated") else "release"
    return f"{EVIDENCE_DIR}/mode-{mode}-{rung}.md"


def scan_badge(root: pathlib.Path) -> CheckResult:
    result = CheckResult("badge")
    readme = root / "README.md"
    text = readme.read_text(encoding="utf-8") if readme.is_file() else ""
    matches = BADGE_RE.findall(text)
    if len(matches) != 1:
        result.findings.append(
            Finding(
                "badge",
                "README.md",
                None,
                "badge-unparseable",
                f"{len(matches)} line(s) match the EP-2 badge contract; exactly one must",
                "the badge is one `status: …` line in a fenced block (D-59)",
            )
        )
        return result.fail()

    badge = matches[0]
    evidence = evidence_path_for(badge)
    file = root / evidence
    if not file.is_file():
        result.findings.append(
            Finding(
                "badge",
                evidence,
                None,
                "evidence-file-absent",
                f"the badge claims `status: {badge}` and its evidence file does not exist",
                "write the evidence file before the badge advances — never after (D-12, D-59)",
            )
        )
        return result.fail()

    body = file.read_text(encoding="utf-8")
    for match in UNTICKED_BOX.finditer(body):
        result.findings.append(
            Finding(
                "badge",
                evidence,
                _line_of(body, match.start()),
                "evidence-checkbox-unticked",
                f"the badge claims `status: {badge}` and this evidence box is unticked",
                "tick the box only when the artifact it names exists, or move the badge down",
            )
        )
    result.note = f"`status: {badge}` -> {evidence}"
    return result.fail()


# ── check 8 — the retired modality term ──────────────────────────────────────


def _bibliographic_spans(root: pathlib.Path, text: str) -> list[tuple[int, int]]:
    """Where a rights-record source identifier or citation title sits in `text`.

    A book's title is bibliographic identity, not this project's self-description
    of itself. D-4 retires an *expansion of this project's name*; D-74 requires
    that every source be citable. The two rules only appear to collide, and the
    collision is resolved from the rights record rather than from judgement: a
    span is bibliographic when it is literally a `source_id` or a citation
    `title` that `sources.yaml` declares. Everything else is a finding.

    Ratified by the project owner on 2026-09-01 as **ruling OD-14**, at exactly
    this scope: never a file, a directory, a pattern or a line. Widening it needs
    a further ruling. The OD-10 exemption table is untouched and still has three
    entries.
    """
    from ..rights.load import load_sources
    from ..rights.model import RightsError
    from ..rights.paths import sources_yaml

    try:
        registry = load_sources(sources_yaml(root))
    except RightsError, OSError:
        return []
    strings = set()
    for source in registry:
        strings.add(source.source_id)
        strings.add(source.citation.title)
    spans = []
    for needle in strings:
        if MODALITY_STEM not in needle.lower():
            continue
        for match in re.finditer(re.escape(needle), text, re.IGNORECASE):
            spans.append((match.start(), match.end()))
    return spans


def scan_modality(root: pathlib.Path) -> CheckResult:
    """A stem sweep with an owner-ratified, reasoned exemption table (OD-10)."""
    result = CheckResult("modality")
    for path in tracked_files(root):
        if is_canary(path):
            continue
        if path in MODALITY_EXEMPTIONS:
            text = read_text(root, path) or ""
            hits = len(MODALITY_RULE.pattern.findall(text))
            if hits:
                result.skips.append(
                    Skip(path, None, "modality-exemption", MODALITY_EXEMPTIONS[path])
                )
            continue
        text = read_text(root, path)
        if text is None:
            continue
        marked = marked_lines(text)
        spans = _bibliographic_spans(root, text)
        for match in MODALITY_RULE.pattern.finditer(text):
            line = _line_of(text, match.start())
            if line in marked:
                result.skips.append(
                    Skip(path, line, MARKER_REASON, "suppressed modality/retired-modality-stem")
                )
                continue
            if any(start <= match.start() and match.end() <= end for start, end in spans):
                result.skips.append(
                    Skip(
                        path,
                        line,
                        "bibliographic-identity",
                        "inside a source identifier or citation title declared in sources.yaml",
                    )
                )
                continue
            result.findings.append(
                Finding(
                    "modality",
                    path,
                    line,
                    MODALITY_RULE.name,
                    MODALITY_RULE.detail,
                    MODALITY_RULE.hint,
                )
            )
    result.note = f"{len(MODALITY_EXEMPTIONS)} exempt file(s), each with a reason"
    return result.fail()


# ── check 9 — shared passages with private planning state ───────────────────


def scan_ledger(root: pathlib.Path) -> CheckResult:
    """Positions and counts inside `DECISIONS.md`. Never a line of `.local/`."""
    result = CheckResult("ledger")
    directory = root / ledger_module.LEDGER_DIR
    decisions = root / "epppsynth" / "DECISIONS.md"
    if not directory.is_dir():
        result.status = SKIPPED
        result.note = "skipped — no ledger present"
        return result
    if not decisions.is_file():
        result.status = SKIPPED
        result.note = "skipped — no decision log present"
        return result

    report = ledger_module.compare(decisions, directory)
    for line in report.outside_published:
        result.findings.append(
            Finding(
                "ledger",
                "epppsynth/DECISIONS.md",
                line,
                "shared-passage-outside-entry",
                "an eight-word sequence here also appears in private planning state, "
                "outside a published decision entry or the index block",
                "publish the settled decision inside an entry, or reword the surrounding prose",
            )
        )
    result.note = report.summary()
    return result.fail()


# ── the allowlist checking itself ────────────────────────────────────────────


#: The checks that read tracked files line by line. A marker can only be earned
#: against one of them, so the self-check is meaningless unless all of them ran.
TEXT_CHECKS: frozenset[str] = frozenset(
    {"secrets", "phi", "protected-text", "identity", "roots", "modality"}
)


def scan_allowlist(root: pathlib.Path, results: Sequence[CheckResult]) -> CheckResult:
    """A marker that suppressed nothing is a hole waiting for a future edit."""
    result = CheckResult(SELF_CHECK)
    ran = {check.check for check in results}
    if not TEXT_CHECKS <= ran:
        result.status = SKIPPED
        missing = ", ".join(sorted(TEXT_CHECKS - ran))
        result.note = f"skipped - a marker is earned against a check that did not run ({missing})"
        return result
    used = {
        (skip.path, skip.line)
        for check in results
        for skip in check.skips
        if skip.reason == MARKER_REASON
    }
    for path in tracked_files(root):
        if is_canary(path):
            continue
        text = read_text(root, path)
        if text is None:
            continue
        for line in sorted(marked_lines(text)):
            if (path, line) not in used:
                result.findings.append(
                    Finding(
                        SELF_CHECK,
                        path,
                        line,
                        "unnecessary-rule-definition-marker",
                        "this line carries the rule-definition marker and matches no rule",
                        "remove the marker; an exemption a file does not need is a future hole",
                    )
                )
    result.note = f"{len(used)} marker(s) in use"
    return result.fail()


# ── the runner ───────────────────────────────────────────────────────────────

_SCANNERS = {
    "secrets": scan_secrets,
    "phi": scan_phi,
    "protected-text": scan_protected_text,
    "identity": scan_identity,
    "roots": scan_roots,
    "rights": scan_rights,
    "badge": scan_badge,
    "modality": scan_modality,
    "ledger": scan_ledger,
}


def run_scan(
    root: pathlib.Path | None = None,
    *,
    history: bool = False,
    checks: Sequence[str] | None = None,
) -> ScanReport:
    """Run the nine checks plus the allowlist self-check, and report everything."""
    base = (root or repo_root()).resolve()
    wanted = tuple(checks) if checks else CHECKS
    report = ScanReport(base, history=history)
    for name in wanted:
        scanner = _SCANNERS[name]
        if name == "secrets":
            report.results.append(scanner(base, history=history))
        else:
            report.results.append(scanner(base))
    report.results.append(scan_allowlist(base, report.results))
    if is_canary(CANARY_ALLOWLIST[0]):  # keeps the reason string used and visible
        report.results[-1].note += f"; canary directory exempt: {CANARY_REASON}"
    return report


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="epppsynth scan",
        description=(
            "Leak-prevention scanners (EP-6). Defense in depth, never proof: the proof is "
            "the pre-publication review packet in epppsynth/docs/pre-publication-checklist.md, "
            "performed by a human and recorded with a date and a commit hash."
        ),
    )
    parser.add_argument(
        "--history",
        action="store_true",
        help="also sweep `git log -p --all` for secrets; CI's job, skipped by the hook for speed",
    )
    parser.add_argument(
        "--fix-hints",
        action="store_true",
        help="print a one-line remedy under each finding",
    )
    parser.add_argument(
        "--check",
        action="append",
        choices=CHECKS,
        metavar="ID",
        help=f"run only this check; repeatable. One of: {', '.join(CHECKS)}",
    )
    args = parser.parse_args(argv)

    # A finding names a path, and a path may hold any character the filesystem
    # allows. The console encoding on the CI runner is not UTF-8 by default, and
    # a scanner that crashes on its own report is a scanner nobody trusts.
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")

    report = run_scan(history=args.history, checks=args.check)
    print(report.render(fix_hints=args.fix_hints))
    return 0 if report.ok else 1


if __name__ == "__main__":  # pragma: no cover - CLI entry
    sys.exit(main())
